# Generated by Django 5.0.9 on 2024-11-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='birdh_date',
        ),
        migrations.AddField(
            model_name='parent',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth_date'),
        ),
    ]
