# Generated by Django 5.0.9 on 2024-11-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_remove_parent_birdh_date_parent_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
